spring:  application:    name: "microservice-students"  datasource:    url: jdbc:mysql://localhost:3306/db_microservicios_examenes?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = UTC    username: root    password: Gdr291074.    driver-class-name: com.mysql.cj.jdbc.Driver  jpa:    database-platform: org.hibernate.dialect.MySQL8Dialect    generate-ddl: true    show-sql: true    hibernate:      ddl-auto: updatelogging:  level:    org:      hibernate:        sql: debug
server:
  port: ${PORT:0}
eureka:  instance:    instance-id: ${spring.application.name}:${random.value}    hostname: ${vcap.application.uris[0]:localhost}
    prefer-ip-address: true
    #lease-renewal-interval-in-seconds: 10
    #lease-expiration-duration-in-seconds: 20
  client:    serviceUrl:
      defaultZone: http://localhost:8761/eureka      